export const locationsData = [
  {
    state: "Nassau County",
    cities: [
      "Westbury",
      "Garden City",
      "Mineola",
      "Hempstead",
      "Valley Stream",
      "Lynbrook",
      "Rockville Centre",
      "Long Beach",
      "Oceanside",
      "Freeport",
      "Merrick",
      "Bellmore",
      "Wantagh",
      "Seaford",
      "Massapequa",
      "Massapequa Park",
      "Hicksville",
      "Syosset",
      "Plainview",
      "Woodbury",
      "Great Neck",
      "Manhasset",
      "Port Washington",
      "Roslyn",
      "Glen Cove",
      "Oyster Bay",
      "East Meadow",
      "Levittown",
      "Bethpage",
      "Old Bethpage",
      "Jericho",
      "Brookville",
      "Locust Valley",
      "Sea Cliff",
      "New Hyde Park",
      "Franklin Square",
      "Baldwin",
    ],
  },
  {
    state: "Suffolk County",
    cities: [
      "Huntington",
      "Huntington Station",
      "Commack",
      "Smithtown",
      "Kings Park",
      "Hauppauge",
      "Ronkonkoma",
      "Lake Ronkonkoma",
      "Patchogue",
      "Bay Shore",
      "Islip",
      "West Islip",
      "East Islip",
      "Amityville",
      "Babylon",
      "West Babylon",
      "North Babylon",
      "Lindenhurst",
      "Copiague",
      "Deer Park",
      "Farmingdale",
      "Cold Spring Harbor",
      "Northport",
      "East Northport",
      "Dix Hills",
      "Melville",
      "Centerport",
      "Port Jefferson",
      "Stony Brook",
      "Setauket",
      "Sayville",
      "Shirley",
      "Center Moriches",
      "Riverhead",
      "Southampton",
      "Hampton Bays",
      "East Hampton",
      "Westhampton Beach",
      "Sag Harbor",
      "Montauk",
    ],
  },
];
