export const locationsData = [
  { state: "Alabama", cities: ["North Birmingham"] },
  { state: "Arizona", cities: ["Chandler", "Scottsdale", "Tucson"] },
  { state: "Arkansas", cities: ["Fort Smith", "Northwest Arkansas"] },
  { state: "California", cities: ["Central San Diego", "East Bay", "Inland Empire", "Irvine", "North Orange County", "Orange County Coastal", "Sacramento Northeast", "San Francisco", "San Joaquin", "Silicon Valley", "The East Bay", "West Contra Costa", "West Los Angeles"] },
  { state: "Colorado", cities: ["Denver Metro", "Denver Tech Center", "Greater Boulder"] },
  { state: "Connecticut", cities: ["Lower Fairfield County"] },
  { state: "Delaware", cities: ["New Castle County"] },
  { state: "Florida", cities: ["Boca Delray", "Central Florida", "East Jacksonville", "East Tampa Bay", "North Miami", "Orlando East", "Palm Beach", "South Broward", "South Miami", "Space Coast", "St Augustine", "SW Florida", "The Villages", "Wesley Chapel"] },
  { state: "Georgia", cities: ["Forsyth", "Greater Augusta", "Marietta", "North Atlanta", "North Fulton", "North Gwinnett Buford", "Savannah Hilton Head", "West Metro Atlanta"] },
  { state: "Idaho", cities: ["Southeast Idaho"] },
  { state: "Illinois", cities: ["Barrington", "Chicago North Shore"] },
  { state: "Indiana", cities: ["North Indianapolis"] },
  { state: "Iowa", cities: ["Des Moines"] },
  { state: "Kansas", cities: ["Topeka", "Wichita"] },
  { state: "Kentucky", cities: ["North Louisville"] },
  { state: "Louisiana", cities: ["New Orleans North Shore", "New Orleans South Shore"] },
  { state: "Massachusetts", cities: ["Northern Massachusetts"] },
  { state: "Michigan", cities: ["Kalamazoo Battle Creek"] },
  { state: "Minnesota", cities: ["Minneapolis Northwest", "Minneapolis West Metro", "South St. Paul"] },
  { state: "Nebraska", cities: ["Omaha"] },
  { state: "Nevada", cities: ["Henderson Las Vegas"] },
  { state: "New Hampshire", cities: ["Southern New Hampshire"] },
  { state: "New Jersey", cities: ["Burlington County", "Princeton", "The Jersey Shore"] },
  { state: "New York", cities: ["Manhattan", "North Nassau County"] },
  { state: "North Carolina", cities: ["Charlotte Central", "Charlotte Southeast", "Jacksonville", "Nags Head", "Raleigh Southwest", "Southeast Raleigh", "Western North Carolina"] },
  { state: "Ohio", cities: ["Akron", "Dayton", "Lorain Erie County", "Medina Cuyahoga", "Northeast Columbus", "West Columbus"] },
  { state: "Oklahoma", cities: ["North Oklahoma City", "South Oklahoma City"] },
  { state: "Oregon", cities: ["Portland South", "Salem Eugene", "Southern Oregon"] },
  { state: "Pennsylvania", cities: ["Central Pennsylvania"] },
  { state: "South Carolina", cities: ["Charleston North", "Charleston South", "Fort Mill", "Greater Augusta", "Greenville Spartanburg"] },
  { state: "Tennessee", cities: ["Cool Springs", "Greater Memphis", "Knoxville", "Middle Tennessee", "Mt Juliet - Lebanon", "Nashville Hendersonville"] },
  { state: "Texas", cities: ["Atascocita Kingwood", "College Station", "Conroe", "Dallas Central", "Dallas East", "Frisco", "McKinney", "North Austin", "Addison", "North DFW", "Northeast Dallas", "Northern San Antonio", "Northwest Houston", "Pearland", "Richardson Garland Rockwall", "San Antonio Hill Country", "Sugar Land", "West Fort Worth", "West Houston"] },
  { state: "Utah", cities: ["Lehi", "Ogden-Farmington", "Salt Lake", "Salt Lake West"] },
  { state: "Virginia", cities: ["Arlington DC", "Northern Virginia"] },
  { state: "Washington", cities: ["Tacoma", "South King County"] },
  { state: "Wisconsin", cities: ["Madison", "Milwaukee South", "North Milwaukee"] }
];